import 'package:path/path.dart' as p;

import '../config.dart';
import '../generated_file.dart';
import '../generator.dart';

List<GeneratedFile> packageTemplates(
  TemplateContext context, {
  required bool includePresentation,
}) {
  final files = <GeneratedFile>[
    GeneratedFile(
      path: p.join(_packageRoot(context.paths.domain), 'pubspec.yaml'),
      content: _domainPubspec(context),
    ),
    GeneratedFile(
      path: p.join(_packageRoot(context.paths.data), 'pubspec.yaml'),
      content: _dataPubspec(context),
    ),
    GeneratedFile(
      path: p.join(_packageRoot(context.paths.di), 'pubspec.yaml'),
      content: _diPubspec(context),
    ),
  ];

  if (includePresentation) {
    files.addAll([
      GeneratedFile(
        path: p.join(_packageRoot(context.paths.presentation), 'pubspec.yaml'),
        content: _presentationPubspec(context),
      ),
      GeneratedFile(
        path: p.join(
            _packageRoot(context.paths.presentation), 'lib', 'main.dart'),
        content: _presentationMain(),
      ),
      GeneratedFile(
        path: p.join(_packageRoot(context.paths.presentation), 'lib', 'widgets',
            '.gitkeep'),
        content: '',
      ),
      GeneratedFile(
        path: p.join(_packageRoot(context.paths.presentation), 'lib', 'pages',
            '.gitkeep'),
        content: '',
      ),
      GeneratedFile(
        path: p.join(_packageRoot(context.paths.presentation), 'lib', 'utils',
            '.gitkeep'),
        content: '',
      ),
      GeneratedFile(
        path: p.join(_packageRoot(context.paths.presentation), 'lib',
            'controllers', '.gitkeep'),
        content: '',
      ),
      GeneratedFile(
        path: p.join(_packageRoot(context.paths.presentation), 'lib',
            'constants', '.gitkeep'),
        content: '',
      ),
      GeneratedFile(
        path: p.join(
          _packageRoot(context.paths.presentation),
          'analysis_options.yaml',
        ),
        content: '''
include: package:flutter_lints/flutter.yaml
''',
      ),
    ]);
  }

  return files;
}

String _domainPubspec(TemplateContext context) {
  return '''
name: ${_packageName(context.paths.domain)}
description: Domain layer generated by clean_architect.
publish_to: none

environment:
  sdk: ^3.6.0
''';
}

String _dataPubspec(TemplateContext context) {
  final dependencies = <String>[
    "  ${_packageName(context.paths.domain)}:",
    '    path: ../${_packageName(context.paths.domain)}',
  ];

  if (context.config.network == NetworkClient.dio) {
    dependencies.add('  dio: ^5.7.0');
  }
  if (context.config.localStorage == LocalStorage.secureStorage) {
    dependencies.insert(0, '  flutter:\n    sdk: flutter');
    dependencies.add('  flutter_secure_storage: ^9.2.2');
  }
  if (context.config.models.useJsonSerializable) {
    dependencies.add('  json_annotation: ^4.9.0');
  }

  return '''
name: ${_packageName(context.paths.data)}
description: Data layer generated by clean_architect.
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
${dependencies.join('\n')}
''';
}

String _diPubspec(TemplateContext context) {
  final dependencies = <String>[
    '  ${_packageName(context.paths.domain)}:',
    '    path: ../${_packageName(context.paths.domain)}',
    '  ${_packageName(context.paths.data)}:',
    '    path: ../${_packageName(context.paths.data)}',
  ];

  if (context.config.dependencyInjection == DependencyInjection.injectable) {
    dependencies.add('  injectable: ^2.5.0');
    dependencies.add('  get_it: ^8.0.2');
  }

  return '''
name: ${_packageName(context.paths.di)}
description: Dependency injection layer generated by clean_architect.
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
${dependencies.join('\n')}
''';
}

String _presentationPubspec(TemplateContext context) {
  final dependencies = <String>[
    '  flutter:',
    '    sdk: flutter',
    "  ${_packageName(context.paths.domain)}:",
    '    path: ../${_packageName(context.paths.domain)}',
    "  ${_packageName(context.paths.data)}:",
    '    path: ../${_packageName(context.paths.data)}',
    "  ${_packageName(context.paths.di)}:",
    '    path: ../${_packageName(context.paths.di)}',
  ];

  if (context.config.stateManagement == StateManagement.getx) {
    dependencies.add('  get: ^4.6.6');
  }

  return '''
name: ${_packageName(context.paths.presentation)}
description: Flutter presentation layer generated by clean_architect.
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
${dependencies.join('\n')}

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
''';
}

String _presentationMain() {
  return '''
import 'package:flutter/material.dart';

void main() {
  runApp(const CleanArchitectApp());
}

class CleanArchitectApp extends StatelessWidget {
  const CleanArchitectApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Clean Architect',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.blue),
        useMaterial3: true,
      ),
      home: const Scaffold(
        body: Center(child: Text('Clean Architect')),
      ),
    );
  }
}
''';
}

String _packageRoot(String libPath) {
  final parts = p.split(p.normalize(libPath));
  final libIndex = parts.indexOf('lib');
  if (libIndex == -1) return libPath;
  return p.joinAll(parts.take(libIndex));
}

String _packageName(String libPath) {
  final parts = p.split(p.normalize(libPath));
  final libIndex = parts.indexOf('lib');
  if (libIndex > 0) return parts[libIndex - 1];
  return p.basename(libPath);
}
